name: Run Unittests

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]
  
jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version
